FROM python:3.14-slim

RUN useradd -m -u 1000 user
USER user
ENV HOME=/home/user PATH=/home/user/.local/bin:$PATH
WORKDIR $HOME/app

#WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 7860

CMD sh -c "python manage.py migrate && gunicorn ecpay_mock.wsgi:application --bind 0.0.0.0:7860"