# Generated by Django 6.0.3 on 2026-06-04 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('user_id', models.IntegerField()),
                ('receiver_name', models.CharField(help_text='收件者姓名', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_trade_no', models.CharField(max_length=50)),
                ('trade_no', models.CharField(max_length=50)),
                ('trade_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('choose_payment', models.CharField(max_length=20)),
                ('payment_type', models.CharField(max_length=20)),
                ('rtn_code', models.IntegerField()),
                ('rtn_msg', models.CharField(max_length=100)),
                ('simulate_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=20)),
                ('merchant_trade_no', models.CharField(max_length=50, unique=True)),
                ('merchant_trade_date', models.DateTimeField()),
                ('trade_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trade_desc', models.CharField(default='購買商品', max_length=200)),
                ('item_name', models.TextField()),
                ('payment_type', models.CharField(max_length=20)),
                ('choose_payment', models.CharField(max_length=20)),
                ('trade_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_code', models.CharField(max_length=3)),
                ('v_account', models.CharField(max_length=20)),
                ('expire_date', models.DateTimeField(default=django.utils.timezone.now, max_length=20)),
                ('status', models.CharField(choices=[('atm_pending', 'ATM_Pending'), ('atm_created', 'ATM_Create'), ('atm_paid', 'ATM_Paid'), ('atm_failed', 'ATM_Failed'), ('atm_cancelled', 'ATM_Cancelled'), ('atm_expired', 'ATM_Expired')], default='ATM_Pending', max_length=20)),
                ('check_mac_value', models.CharField(blank=True, max_length=128, null=True)),
                ('return_url', models.URLField(blank=True, null=True)),
                ('payment_info_url', models.URLField(blank=True, null=True)),
                ('order_result_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
