"""
Django settings for ecpay_mock project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.utils.csp import CSP
#import django

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#print(f"Django version: {django.__version__}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-y=)$9*krere26k&lc9wepbw=ytdsaj-ecxbga6x#(krgum(j@c'
# 優先讀取環境變數，讀不到就用後面的預設值（注意：正式上線時務必在環境變數中設定 SECRET_KEY）
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-y=)$9*krere26k&lc9wepbw=ytdsaj-ecxbga6x#(krgum(j@c')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

BACKEND_URL = ""

if "SPACE_HOST" in os.environ:
    # 優先使用官方直接提供的完整網域 (例如: monzid1-e-commerce.hf.space)
    BACKEND_URL = f"https://{os.environ.get('SPACE_HOST')}"
elif "SPACE_ID" in os.environ:
    # 備用方案：如果只有 SPACE_ID，手動轉換拼湊
    space_id = os.environ.get("SPACE_ID")
    subdomain = space_id.replace("/", "-").replace("_", "-").lower()
    BACKEND_URL = f"https://{subdomain}.hf.space"
else:
    # 本地開發環境
    BACKEND_URL = "http://127.0.0.1:8001"

ALLOWED_HOSTS = [
	'monzid1-e-commerce.hf.space',
	'proxy.spaces.internal.huggingface.tech'
]

# 關鍵: 允許Hugging Face 的Iframe 嵌入你的網站,否則畫面會空白
#X_FRAME_OPTIONS = "ALLOW-FROM https://huggingface.co"

# 加上這行：允許 Django 讀取 X-Forwarded-Host 標頭
USE_X_FORWARDED_HOST = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gateway',          # 你的 fake 綠界 app
    'corsheaders',      # 新增 CORS 支援
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 放在最前面
	'django.middleware.csrf.CsrfViewMiddleware',
#    'django.middleware.security.SecurityMiddleware',
	'django.middleware.csp.ContentSecurityPolicyMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CSP 設定（包含允許 HuggingFace iframe）
SECURE_CSP = {
    "default-src": [CSP.SELF],
    "style-src": [CSP.SELF, CSP.UNSAFE_INLINE],   # 允許 inline style   
    "script-src": [CSP.SELF, CSP.UNSAFE_INLINE],  # 允許 inline script
    "img-src": [CSP.SELF, "https:"],
    "frame-ancestors": ["https://huggingface.co"],  # 允許 HF 嵌入
}

ROOT_URLCONF = 'ecpay_mock.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
				'django.template.context_processors.csp',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecpay_mock.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hant"

TIME_ZONE = "Asia/Taipei"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"   # 加這行
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SITE_ID = 2

# 綠界測試環境
ECPAY_HASH_KEY = "pwFHCqoQZGmho4w6"
ECPAY_HASH_IV = "EkRm7iFT261dpevs"

# -------------------------------
# 🔑 CORS & CSRF 設定
# -------------------------------

# 允許跨域來源 (前端網址)
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
	"https://*.hf.space",
	"https://huggingface.co",
#	"https://huggingface.co/spaces/monzid1-ecommerce.hf.space",
#	"https://huggingface.co/spaces/monzid1-ecpay-mock.hf.space",
#	"https://huggingface.co/spaces/monzid1-bank-site.hf.space",
#    "http://127.0.0.1:8000",   # React/Vue 本地端 3000
#    "http://localhost:8000",
#    "http://127.0.0.1:8002",   # React/Vue 本地端 3000
#    "http://localhost:8002",
]

# 如果要允許所有來源 (開發用)
# CORS_ALLOW_ALL_ORIGINS = False
# 確保 Cookie 只能透過 HTTPS 傳輸
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# 允許跨站（Cross-site）請求攜帶 Cookie (解決 iframe 嵌入問題)
CSRF_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SAMESITE = 'None'

# 允許跨域攜帶 Cookie
CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True

# CSRF 白名單 (允許的前端來源)
# 允許 Hugging Face Spaces 的網域進行 CSRF 驗證
CSRF_TRUSTED_ORIGINS = [
    "https://*.hf.space",
    "https://huggingface.co",
]

# 如果你使用的是較新版的 Django (例如 4.x/5.x/6.x)，建議也加上這行
# 允許跨域傳送 Cookie
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF 白名單 (允許的前端來源)
#CSRF_TRUSTED_ORIGINS = [
#	"https://*.hf.space",
#	"https://huggingface.co",
#	"https://huggingface.co/spaces/monzid1-ecommerce.hf.space",
#	"https://huggingface.co/spaces/monzid1-ecpay-mock.hf.space",
#	"https://huggingface.co/spaces/monzid1-bank-site.hf.space",
#    "http://127.0.0.1:8000",
#    "http://localhost:8000",
#    "http://127.0.0.1:8002",   # React/Vue 本地端 3000
#    "http://localhost:8002",
#]
